server:
  port: 9006

spring:
  main:
    lazy-initialization: true
  application:
    name: rsvp-collection-service
  config:
    import: optional:configserver:http://config-server.cloud-interview.in/

management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - refresh
          - info
          - metrics
          - env
          - mappings
          - beans
          - shutdown
          - prometheus
      base-path: /internal
